name: TheBrewingMarket
version: '2.2.2'
authors:
  - CesarCosmico
main: com.cesarcosmico.thebrewingmarket.TheBrewingMarketPlugin
description: Sell your TheBrewingProject brews for money
api-version: '26.1'

dependencies:
  server:
    Vault:
      load: BEFORE
      required: true
      join-classpath: true
    TheBrewingProject:
      load: BEFORE
      required: false
      join-classpath: true
    BreweryX:
      load: BEFORE
      required: false
      join-classpath: true
    PlaceholderAPI:
      load: BEFORE
      required: false
      join-classpath: true

permissions:
  thebrewingmarket.*:
    description: Full access to TheBrewingMarket
    default: op
    children:
      thebrewingmarket.use: true
      thebrewingmarket.admin: true
      thebrewingmarket.shulker: true
      thebrewingmarket.history: true

  thebrewingmarket.admin:
    description: Allows reloading TheBrewingMarket config
    default: op

  thebrewingmarket.history:
    description: Allows viewing sell history of any player
    default: op

  thebrewingmarket.use:
    description: Allows using TheBrewingMarket
    default: true

  thebrewingmarket.shulker:
    description: Allows selling brews from inside shulker boxes
    default: true
